/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface ArticleVersionResponse
 */
export interface ArticleVersionResponse {
    /**
     * 
     * @type {number}
     * @memberof ArticleVersionResponse
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleVersionResponse
     */
    versionNumber?: number;
    /**
     * 
     * @type {Date}
     * @memberof ArticleVersionResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {UserResponse}
     * @memberof ArticleVersionResponse
     */
    createdBy?: UserResponse;
    /**
     * 
     * @type {string}
     * @memberof ArticleVersionResponse
     */
    content?: string;
}

/**
 * Check if a given object implements the ArticleVersionResponse interface.
 */
export function instanceOfArticleVersionResponse(value: object): value is ArticleVersionResponse {
    return true;
}

export function ArticleVersionResponseFromJSON(json: any): ArticleVersionResponse {
    return ArticleVersionResponseFromJSONTyped(json, false);
}

export function ArticleVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'versionNumber': json['versionNumber'] == null ? undefined : json['versionNumber'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : UserResponseFromJSON(json['createdBy']),
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function ArticleVersionResponseToJSON(json: any): ArticleVersionResponse {
    return ArticleVersionResponseToJSONTyped(json, false);
}

export function ArticleVersionResponseToJSONTyped(value?: ArticleVersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'versionNumber': value['versionNumber'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': UserResponseToJSON(value['createdBy']),
        'content': value['content'],
    };
}

