/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';
import type { CategoryResponse } from './CategoryResponse';
import {
    CategoryResponseFromJSON,
    CategoryResponseFromJSONTyped,
    CategoryResponseToJSON,
    CategoryResponseToJSONTyped,
} from './CategoryResponse';

/**
 * 
 * @export
 * @interface ArticleDetailResponse
 */
export interface ArticleDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof ArticleDetailResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleDetailResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleDetailResponse
     */
    articleState?: ArticleDetailResponseArticleStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof ArticleDetailResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ArticleDetailResponse
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleDetailResponse
     */
    currentVersion?: number;
    /**
     * 
     * @type {UserResponse}
     * @memberof ArticleDetailResponse
     */
    author?: UserResponse;
    /**
     * 
     * @type {UserResponse}
     * @memberof ArticleDetailResponse
     */
    editor?: UserResponse;
    /**
     * 
     * @type {Set<CategoryResponse>}
     * @memberof ArticleDetailResponse
     */
    categories?: Set<CategoryResponse>;
}


/**
 * @export
 */
export const ArticleDetailResponseArticleStateEnum = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Published: 'PUBLISHED',
    Deleted: 'DELETED'
} as const;
export type ArticleDetailResponseArticleStateEnum = typeof ArticleDetailResponseArticleStateEnum[keyof typeof ArticleDetailResponseArticleStateEnum];


/**
 * Check if a given object implements the ArticleDetailResponse interface.
 */
export function instanceOfArticleDetailResponse(value: object): value is ArticleDetailResponse {
    return true;
}

export function ArticleDetailResponseFromJSON(json: any): ArticleDetailResponse {
    return ArticleDetailResponseFromJSONTyped(json, false);
}

export function ArticleDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'articleState': json['articleState'] == null ? undefined : json['articleState'],
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'content': json['content'] == null ? undefined : json['content'],
        'currentVersion': json['currentVersion'] == null ? undefined : json['currentVersion'],
        'author': json['author'] == null ? undefined : UserResponseFromJSON(json['author']),
        'editor': json['editor'] == null ? undefined : UserResponseFromJSON(json['editor']),
        'categories': json['categories'] == null ? undefined : (new Set((json['categories'] as Array<any>).map(CategoryResponseFromJSON))),
    };
}

export function ArticleDetailResponseToJSON(json: any): ArticleDetailResponse {
    return ArticleDetailResponseToJSONTyped(json, false);
}

export function ArticleDetailResponseToJSONTyped(value?: ArticleDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'articleState': value['articleState'],
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'content': value['content'],
        'currentVersion': value['currentVersion'],
        'author': UserResponseToJSON(value['author']),
        'editor': UserResponseToJSON(value['editor']),
        'categories': value['categories'] == null ? undefined : (Array.from(value['categories'] as Set<any>).map(CategoryResponseToJSON)),
    };
}

