/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTicketRequest
 */
export interface CreateTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTicketRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTicketRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTicketRequest
     */
    assigneeUsername: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTicketRequest
     */
    articleId: number;
}

/**
 * Check if a given object implements the CreateTicketRequest interface.
 */
export function instanceOfCreateTicketRequest(value: object): value is CreateTicketRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('assigneeUsername' in value) || value['assigneeUsername'] === undefined) return false;
    if (!('articleId' in value) || value['articleId'] === undefined) return false;
    return true;
}

export function CreateTicketRequestFromJSON(json: any): CreateTicketRequest {
    return CreateTicketRequestFromJSONTyped(json, false);
}

export function CreateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'assigneeUsername': json['assigneeUsername'],
        'articleId': json['articleId'],
    };
}

export function CreateTicketRequestToJSON(json: any): CreateTicketRequest {
    return CreateTicketRequestToJSONTyped(json, false);
}

export function CreateTicketRequestToJSONTyped(value?: CreateTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'assigneeUsername': value['assigneeUsername'],
        'articleId': value['articleId'],
    };
}

