/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateArticleRequest
 */
export interface CreateArticleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateArticleRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateArticleRequest
     */
    articleState: CreateArticleRequestArticleStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof CreateArticleRequest
     */
    publishedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateArticleRequest
     */
    content: string;
    /**
     * 
     * @type {Set<number>}
     * @memberof CreateArticleRequest
     */
    categoryIds: Set<number>;
    /**
     * 
     * @type {string}
     * @memberof CreateArticleRequest
     */
    editorUsername?: string;
}


/**
 * @export
 */
export const CreateArticleRequestArticleStateEnum = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Published: 'PUBLISHED',
    Deleted: 'DELETED'
} as const;
export type CreateArticleRequestArticleStateEnum = typeof CreateArticleRequestArticleStateEnum[keyof typeof CreateArticleRequestArticleStateEnum];


/**
 * Check if a given object implements the CreateArticleRequest interface.
 */
export function instanceOfCreateArticleRequest(value: object): value is CreateArticleRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('articleState' in value) || value['articleState'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('categoryIds' in value) || value['categoryIds'] === undefined) return false;
    return true;
}

export function CreateArticleRequestFromJSON(json: any): CreateArticleRequest {
    return CreateArticleRequestFromJSONTyped(json, false);
}

export function CreateArticleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArticleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'articleState': json['articleState'],
        'publishedAt': (new Date(json['publishedAt'])),
        'content': json['content'],
        'categoryIds': new Set(json['categoryIds']),
        'editorUsername': json['editorUsername'] == null ? undefined : json['editorUsername'],
    };
}

export function CreateArticleRequestToJSON(json: any): CreateArticleRequest {
    return CreateArticleRequestToJSONTyped(json, false);
}

export function CreateArticleRequestToJSONTyped(value?: CreateArticleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'articleState': value['articleState'],
        'publishedAt': value['publishedAt'].toISOString(),
        'content': value['content'],
        'categoryIds': Array.from(value['categoryIds'] as Set<any>),
        'editorUsername': value['editorUsername'],
    };
}

