/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTicketCommentRequest
 */
export interface CreateTicketCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTicketCommentRequest
     */
    content: string;
}

/**
 * Check if a given object implements the CreateTicketCommentRequest interface.
 */
export function instanceOfCreateTicketCommentRequest(value: object): value is CreateTicketCommentRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateTicketCommentRequestFromJSON(json: any): CreateTicketCommentRequest {
    return CreateTicketCommentRequestFromJSONTyped(json, false);
}

export function CreateTicketCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTicketCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function CreateTicketCommentRequestToJSON(json: any): CreateTicketCommentRequest {
    return CreateTicketCommentRequestToJSONTyped(json, false);
}

export function CreateTicketCommentRequestToJSONTyped(value?: CreateTicketCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

