/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageResponse
 */
export interface ImageResponse {
    /**
     * 
     * @type {number}
     * @memberof ImageResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ImageResponse
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageResponse
     */
    originalFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageResponse
     */
    contentType?: string;
    /**
     * 
     * @type {number}
     * @memberof ImageResponse
     */
    fileSize?: number;
    /**
     * 
     * @type {Date}
     * @memberof ImageResponse
     */
    uploadedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ImageResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the ImageResponse interface.
 */
export function instanceOfImageResponse(value: object): value is ImageResponse {
    return true;
}

export function ImageResponseFromJSON(json: any): ImageResponse {
    return ImageResponseFromJSONTyped(json, false);
}

export function ImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'originalFilename': json['originalFilename'] == null ? undefined : json['originalFilename'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'uploadedAt': json['uploadedAt'] == null ? undefined : (new Date(json['uploadedAt'])),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ImageResponseToJSON(json: any): ImageResponse {
    return ImageResponseToJSONTyped(json, false);
}

export function ImageResponseToJSONTyped(value?: ImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'filename': value['filename'],
        'originalFilename': value['originalFilename'],
        'contentType': value['contentType'],
        'fileSize': value['fileSize'],
        'uploadedAt': value['uploadedAt'] == null ? value['uploadedAt'] : value['uploadedAt'].toISOString(),
        'url': value['url'],
    };
}

