/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleResponse } from './ArticleResponse';
import {
    ArticleResponseFromJSON,
    ArticleResponseFromJSONTyped,
    ArticleResponseToJSON,
    ArticleResponseToJSONTyped,
} from './ArticleResponse';

/**
 * 
 * @export
 * @interface PaginatedArticleResponse
 */
export interface PaginatedArticleResponse {
    /**
     * 
     * @type {Array<ArticleResponse>}
     * @memberof PaginatedArticleResponse
     */
    articles?: Array<ArticleResponse>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedArticleResponse interface.
 */
export function instanceOfPaginatedArticleResponse(value: object): value is PaginatedArticleResponse {
    return true;
}

export function PaginatedArticleResponseFromJSON(json: any): PaginatedArticleResponse {
    return PaginatedArticleResponseFromJSONTyped(json, false);
}

export function PaginatedArticleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedArticleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'articles': json['articles'] == null ? undefined : ((json['articles'] as Array<any>).map(ArticleResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedArticleResponseToJSON(json: any): PaginatedArticleResponse {
    return PaginatedArticleResponseToJSONTyped(json, false);
}

export function PaginatedArticleResponseToJSONTyped(value?: PaginatedArticleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'articles': value['articles'] == null ? undefined : ((value['articles'] as Array<any>).map(ArticleResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

