/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryResponse } from './CategoryResponse';
import {
    CategoryResponseFromJSON,
    CategoryResponseFromJSONTyped,
    CategoryResponseToJSON,
    CategoryResponseToJSONTyped,
} from './CategoryResponse';

/**
 * 
 * @export
 * @interface PaginatedCategoryResponse
 */
export interface PaginatedCategoryResponse {
    /**
     * 
     * @type {Array<CategoryResponse>}
     * @memberof PaginatedCategoryResponse
     */
    categories?: Array<CategoryResponse>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedCategoryResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedCategoryResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedCategoryResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedCategoryResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedCategoryResponse interface.
 */
export function instanceOfPaginatedCategoryResponse(value: object): value is PaginatedCategoryResponse {
    return true;
}

export function PaginatedCategoryResponseFromJSON(json: any): PaginatedCategoryResponse {
    return PaginatedCategoryResponseFromJSONTyped(json, false);
}

export function PaginatedCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedCategoryResponseToJSON(json: any): PaginatedCategoryResponse {
    return PaginatedCategoryResponseToJSONTyped(json, false);
}

export function PaginatedCategoryResponseToJSONTyped(value?: PaginatedCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

