/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketResponse } from './TicketResponse';
import {
    TicketResponseFromJSON,
    TicketResponseFromJSONTyped,
    TicketResponseToJSON,
    TicketResponseToJSONTyped,
} from './TicketResponse';

/**
 * 
 * @export
 * @interface PaginatedTicketResponse
 */
export interface PaginatedTicketResponse {
    /**
     * 
     * @type {Array<TicketResponse>}
     * @memberof PaginatedTicketResponse
     */
    tickets?: Array<TicketResponse>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedTicketResponse interface.
 */
export function instanceOfPaginatedTicketResponse(value: object): value is PaginatedTicketResponse {
    return true;
}

export function PaginatedTicketResponseFromJSON(json: any): PaginatedTicketResponse {
    return PaginatedTicketResponseFromJSONTyped(json, false);
}

export function PaginatedTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tickets': json['tickets'] == null ? undefined : ((json['tickets'] as Array<any>).map(TicketResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedTicketResponseToJSON(json: any): PaginatedTicketResponse {
    return PaginatedTicketResponseToJSONTyped(json, false);
}

export function PaginatedTicketResponseToJSONTyped(value?: PaginatedTicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tickets': value['tickets'] == null ? undefined : ((value['tickets'] as Array<any>).map(TicketResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

