/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketCommentResponse } from './TicketCommentResponse';
import {
    TicketCommentResponseFromJSON,
    TicketCommentResponseFromJSONTyped,
    TicketCommentResponseToJSON,
    TicketCommentResponseToJSONTyped,
} from './TicketCommentResponse';

/**
 * 
 * @export
 * @interface PaginatedTicketCommentResponse
 */
export interface PaginatedTicketCommentResponse {
    /**
     * 
     * @type {Array<TicketCommentResponse>}
     * @memberof PaginatedTicketCommentResponse
     */
    comments?: Array<TicketCommentResponse>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketCommentResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketCommentResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketCommentResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketCommentResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedTicketCommentResponse interface.
 */
export function instanceOfPaginatedTicketCommentResponse(value: object): value is PaginatedTicketCommentResponse {
    return true;
}

export function PaginatedTicketCommentResponseFromJSON(json: any): PaginatedTicketCommentResponse {
    return PaginatedTicketCommentResponseFromJSONTyped(json, false);
}

export function PaginatedTicketCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTicketCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(TicketCommentResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedTicketCommentResponseToJSON(json: any): PaginatedTicketCommentResponse {
    return PaginatedTicketCommentResponseToJSONTyped(json, false);
}

export function PaginatedTicketCommentResponseToJSONTyped(value?: PaginatedTicketCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(TicketCommentResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

