/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleVersionResponse } from './ArticleVersionResponse';
import {
    ArticleVersionResponseFromJSON,
    ArticleVersionResponseFromJSONTyped,
    ArticleVersionResponseToJSON,
    ArticleVersionResponseToJSONTyped,
} from './ArticleVersionResponse';

/**
 * 
 * @export
 * @interface PaginatedArticleVersionResponse
 */
export interface PaginatedArticleVersionResponse {
    /**
     * 
     * @type {Array<ArticleVersionResponse>}
     * @memberof PaginatedArticleVersionResponse
     */
    versions?: Array<ArticleVersionResponse>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleVersionResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleVersionResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleVersionResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedArticleVersionResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedArticleVersionResponse interface.
 */
export function instanceOfPaginatedArticleVersionResponse(value: object): value is PaginatedArticleVersionResponse {
    return true;
}

export function PaginatedArticleVersionResponseFromJSON(json: any): PaginatedArticleVersionResponse {
    return PaginatedArticleVersionResponseFromJSONTyped(json, false);
}

export function PaginatedArticleVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedArticleVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(ArticleVersionResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedArticleVersionResponseToJSON(json: any): PaginatedArticleVersionResponse {
    return PaginatedArticleVersionResponseToJSONTyped(json, false);
}

export function PaginatedArticleVersionResponseToJSONTyped(value?: PaginatedArticleVersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(ArticleVersionResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

