/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageResponse } from './ImageResponse';
import {
    ImageResponseFromJSON,
    ImageResponseFromJSONTyped,
    ImageResponseToJSON,
    ImageResponseToJSONTyped,
} from './ImageResponse';

/**
 * 
 * @export
 * @interface PaginatedImageResponse
 */
export interface PaginatedImageResponse {
    /**
     * 
     * @type {Array<ImageResponse>}
     * @memberof PaginatedImageResponse
     */
    images?: Array<ImageResponse>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedImageResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedImageResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedImageResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedImageResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedImageResponse interface.
 */
export function instanceOfPaginatedImageResponse(value: object): value is PaginatedImageResponse {
    return true;
}

export function PaginatedImageResponseFromJSON(json: any): PaginatedImageResponse {
    return PaginatedImageResponseFromJSONTyped(json, false);
}

export function PaginatedImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedImageResponseToJSON(json: any): PaginatedImageResponse {
    return PaginatedImageResponseToJSONTyped(json, false);
}

export function PaginatedImageResponseToJSONTyped(value?: PaginatedImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

