/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface PaginatedUserResponse
 */
export interface PaginatedUserResponse {
    /**
     * 
     * @type {Array<UserResponse>}
     * @memberof PaginatedUserResponse
     */
    users?: Array<UserResponse>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUserResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUserResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUserResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUserResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginatedUserResponse interface.
 */
export function instanceOfPaginatedUserResponse(value: object): value is PaginatedUserResponse {
    return true;
}

export function PaginatedUserResponseFromJSON(json: any): PaginatedUserResponse {
    return PaginatedUserResponseFromJSONTyped(json, false);
}

export function PaginatedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PaginatedUserResponseToJSON(json: any): PaginatedUserResponse {
    return PaginatedUserResponseToJSONTyped(json, false);
}

export function PaginatedUserResponseToJSONTyped(value?: PaginatedUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

