/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetCodeResponse
 */
export interface PasswordResetCodeResponse {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetCodeResponse
     */
    code?: string;
}

/**
 * Check if a given object implements the PasswordResetCodeResponse interface.
 */
export function instanceOfPasswordResetCodeResponse(value: object): value is PasswordResetCodeResponse {
    return true;
}

export function PasswordResetCodeResponseFromJSON(json: any): PasswordResetCodeResponse {
    return PasswordResetCodeResponseFromJSONTyped(json, false);
}

export function PasswordResetCodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetCodeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function PasswordResetCodeResponseToJSON(json: any): PasswordResetCodeResponse {
    return PasswordResetCodeResponseToJSONTyped(json, false);
}

export function PasswordResetCodeResponseToJSONTyped(value?: PasswordResetCodeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

