/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetConfirmRequest
 */
export interface PasswordResetConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetConfirmRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PasswordResetConfirmRequest interface.
 */
export function instanceOfPasswordResetConfirmRequest(value: object): value is PasswordResetConfirmRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function PasswordResetConfirmRequestFromJSON(json: any): PasswordResetConfirmRequest {
    return PasswordResetConfirmRequestFromJSONTyped(json, false);
}

export function PasswordResetConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'newPassword': json['newPassword'],
    };
}

export function PasswordResetConfirmRequestToJSON(json: any): PasswordResetConfirmRequest {
    return PasswordResetConfirmRequestToJSONTyped(json, false);
}

export function PasswordResetConfirmRequestToJSONTyped(value?: PasswordResetConfirmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'newPassword': value['newPassword'],
    };
}

