/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordChangeRequest
 */
export interface PasswordChangeRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeRequest
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PasswordChangeRequest interface.
 */
export function instanceOfPasswordChangeRequest(value: object): value is PasswordChangeRequest {
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function PasswordChangeRequestFromJSON(json: any): PasswordChangeRequest {
    return PasswordChangeRequestFromJSONTyped(json, false);
}

export function PasswordChangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordChangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'oldPassword': json['oldPassword'],
        'newPassword': json['newPassword'],
    };
}

export function PasswordChangeRequestToJSON(json: any): PasswordChangeRequest {
    return PasswordChangeRequestToJSONTyped(json, false);
}

export function PasswordChangeRequestToJSONTyped(value?: PasswordChangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldPassword': value['oldPassword'],
        'newPassword': value['newPassword'],
    };
}

