/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface TicketCommentResponse
 */
export interface TicketCommentResponse {
    /**
     * 
     * @type {number}
     * @memberof TicketCommentResponse
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof TicketCommentResponse
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketCommentResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketCommentResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {UserResponse}
     * @memberof TicketCommentResponse
     */
    author?: UserResponse;
}

/**
 * Check if a given object implements the TicketCommentResponse interface.
 */
export function instanceOfTicketCommentResponse(value: object): value is TicketCommentResponse {
    return true;
}

export function TicketCommentResponseFromJSON(json: any): TicketCommentResponse {
    return TicketCommentResponseFromJSONTyped(json, false);
}

export function TicketCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'author': json['author'] == null ? undefined : UserResponseFromJSON(json['author']),
    };
}

export function TicketCommentResponseToJSON(json: any): TicketCommentResponse {
    return TicketCommentResponseToJSONTyped(json, false);
}

export function TicketCommentResponseToJSONTyped(value?: TicketCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'author': UserResponseToJSON(value['author']),
    };
}

