/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface TicketResponse
 */
export interface TicketResponse {
    /**
     * 
     * @type {number}
     * @memberof TicketResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TicketResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketResponse
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketResponse
     */
    state?: TicketResponseStateEnum;
    /**
     * 
     * @type {UserResponse}
     * @memberof TicketResponse
     */
    assignee?: UserResponse;
    /**
     * 
     * @type {UserResponse}
     * @memberof TicketResponse
     */
    author?: UserResponse;
    /**
     * 
     * @type {number}
     * @memberof TicketResponse
     */
    articleId?: number;
}


/**
 * @export
 */
export const TicketResponseStateEnum = {
    Open: 'OPEN',
    InProgress: 'IN_PROGRESS',
    ForReview: 'FOR_REVIEW',
    Approved: 'APPROVED',
    Published: 'PUBLISHED'
} as const;
export type TicketResponseStateEnum = typeof TicketResponseStateEnum[keyof typeof TicketResponseStateEnum];


/**
 * Check if a given object implements the TicketResponse interface.
 */
export function instanceOfTicketResponse(value: object): value is TicketResponse {
    return true;
}

export function TicketResponseFromJSON(json: any): TicketResponse {
    return TicketResponseFromJSONTyped(json, false);
}

export function TicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'state': json['state'] == null ? undefined : json['state'],
        'assignee': json['assignee'] == null ? undefined : UserResponseFromJSON(json['assignee']),
        'author': json['author'] == null ? undefined : UserResponseFromJSON(json['author']),
        'articleId': json['articleId'] == null ? undefined : json['articleId'],
    };
}

export function TicketResponseToJSON(json: any): TicketResponse {
    return TicketResponseToJSONTyped(json, false);
}

export function TicketResponseToJSONTyped(value?: TicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'state': value['state'],
        'assignee': UserResponseToJSON(value['assignee']),
        'author': UserResponseToJSON(value['author']),
        'articleId': value['articleId'],
    };
}

