/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransitionTicketRequest
 */
export interface TransitionTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof TransitionTicketRequest
     */
    targetState: TransitionTicketRequestTargetStateEnum;
    /**
     * 
     * @type {string}
     * @memberof TransitionTicketRequest
     */
    comment?: string;
}


/**
 * @export
 */
export const TransitionTicketRequestTargetStateEnum = {
    Open: 'OPEN',
    InProgress: 'IN_PROGRESS',
    ForReview: 'FOR_REVIEW',
    Approved: 'APPROVED',
    Published: 'PUBLISHED'
} as const;
export type TransitionTicketRequestTargetStateEnum = typeof TransitionTicketRequestTargetStateEnum[keyof typeof TransitionTicketRequestTargetStateEnum];


/**
 * Check if a given object implements the TransitionTicketRequest interface.
 */
export function instanceOfTransitionTicketRequest(value: object): value is TransitionTicketRequest {
    if (!('targetState' in value) || value['targetState'] === undefined) return false;
    return true;
}

export function TransitionTicketRequestFromJSON(json: any): TransitionTicketRequest {
    return TransitionTicketRequestFromJSONTyped(json, false);
}

export function TransitionTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitionTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetState': json['targetState'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function TransitionTicketRequestToJSON(json: any): TransitionTicketRequest {
    return TransitionTicketRequestToJSONTyped(json, false);
}

export function TransitionTicketRequestToJSONTyped(value?: TransitionTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetState': value['targetState'],
        'comment': value['comment'],
    };
}

