/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateArticleRequest
 */
export interface UpdateArticleRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateArticleRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateArticleRequest
     */
    articleState: UpdateArticleRequestArticleStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof UpdateArticleRequest
     */
    publishedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateArticleRequest
     */
    content: string;
    /**
     * 
     * @type {Set<number>}
     * @memberof UpdateArticleRequest
     */
    categoryIds: Set<number>;
    /**
     * 
     * @type {string}
     * @memberof UpdateArticleRequest
     */
    editorUsername?: string;
}


/**
 * @export
 */
export const UpdateArticleRequestArticleStateEnum = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Published: 'PUBLISHED',
    Deleted: 'DELETED'
} as const;
export type UpdateArticleRequestArticleStateEnum = typeof UpdateArticleRequestArticleStateEnum[keyof typeof UpdateArticleRequestArticleStateEnum];


/**
 * Check if a given object implements the UpdateArticleRequest interface.
 */
export function instanceOfUpdateArticleRequest(value: object): value is UpdateArticleRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('articleState' in value) || value['articleState'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('categoryIds' in value) || value['categoryIds'] === undefined) return false;
    return true;
}

export function UpdateArticleRequestFromJSON(json: any): UpdateArticleRequest {
    return UpdateArticleRequestFromJSONTyped(json, false);
}

export function UpdateArticleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateArticleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'articleState': json['articleState'],
        'publishedAt': (new Date(json['publishedAt'])),
        'content': json['content'],
        'categoryIds': new Set(json['categoryIds']),
        'editorUsername': json['editorUsername'] == null ? undefined : json['editorUsername'],
    };
}

export function UpdateArticleRequestToJSON(json: any): UpdateArticleRequest {
    return UpdateArticleRequestToJSONTyped(json, false);
}

export function UpdateArticleRequestToJSONTyped(value?: UpdateArticleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'articleState': value['articleState'],
        'publishedAt': value['publishedAt'].toISOString(),
        'content': value['content'],
        'categoryIds': Array.from(value['categoryIds'] as Set<any>),
        'editorUsername': value['editorUsername'],
    };
}

