/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTicketCommentRequest
 */
export interface UpdateTicketCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketCommentRequest
     */
    content: string;
}

/**
 * Check if a given object implements the UpdateTicketCommentRequest interface.
 */
export function instanceOfUpdateTicketCommentRequest(value: object): value is UpdateTicketCommentRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function UpdateTicketCommentRequestFromJSON(json: any): UpdateTicketCommentRequest {
    return UpdateTicketCommentRequestFromJSONTyped(json, false);
}

export function UpdateTicketCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTicketCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function UpdateTicketCommentRequestToJSON(json: any): UpdateTicketCommentRequest {
    return UpdateTicketCommentRequestToJSONTyped(json, false);
}

export function UpdateTicketCommentRequestToJSONTyped(value?: UpdateTicketCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

