/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTicketRequest
 */
export interface UpdateTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    assigneeUsername?: string;
}

/**
 * Check if a given object implements the UpdateTicketRequest interface.
 */
export function instanceOfUpdateTicketRequest(value: object): value is UpdateTicketRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function UpdateTicketRequestFromJSON(json: any): UpdateTicketRequest {
    return UpdateTicketRequestFromJSONTyped(json, false);
}

export function UpdateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'assigneeUsername': json['assigneeUsername'] == null ? undefined : json['assigneeUsername'],
    };
}

export function UpdateTicketRequestToJSON(json: any): UpdateTicketRequest {
    return UpdateTicketRequestToJSONTyped(json, false);
}

export function UpdateTicketRequestToJSONTyped(value?: UpdateTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'assigneeUsername': value['assigneeUsername'],
    };
}

