/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorResponse
 */
export interface ValidationErrorResponse {
    /**
     * 
     * @type {number}
     * @memberof ValidationErrorResponse
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponse
     */
    path?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidationErrorResponse
     */
    validationErrors?: Array<string>;
}

/**
 * Check if a given object implements the ValidationErrorResponse interface.
 */
export function instanceOfValidationErrorResponse(value: object): value is ValidationErrorResponse {
    return true;
}

export function ValidationErrorResponseFromJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseFromJSONTyped(json, false);
}

export function ValidationErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
        'path': json['path'] == null ? undefined : json['path'],
        'validationErrors': json['validationErrors'] == null ? undefined : json['validationErrors'],
    };
}

export function ValidationErrorResponseToJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseToJSONTyped(json, false);
}

export function ValidationErrorResponseToJSONTyped(value?: ValidationErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': value['error'],
        'message': value['message'],
        'path': value['path'],
        'validationErrors': value['validationErrors'],
    };
}

