/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArticleVersionResponse,
  ErrorResponse,
  Pageable,
  PaginatedArticleVersionResponse,
} from '../models/index';
import {
    ArticleVersionResponseFromJSON,
    ArticleVersionResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PageableFromJSON,
    PageableToJSON,
    PaginatedArticleVersionResponseFromJSON,
    PaginatedArticleVersionResponseToJSON,
} from '../models/index';

export interface GetArticleVersionRequest {
    articleId: number;
    versionNumber: number;
}

export interface ListArticleVersionsRequest {
    articleId: number;
    pageable: Pageable;
}

/**
 * 
 */
export class ArticleVersionsApi extends runtime.BaseAPI {

    /**
     * Get a specific version of an article with content.
     * Get version
     */
    async getArticleVersionRaw(requestParameters: GetArticleVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArticleVersionResponse>> {
        if (requestParameters['articleId'] == null) {
            throw new runtime.RequiredError(
                'articleId',
                'Required parameter "articleId" was null or undefined when calling getArticleVersion().'
            );
        }

        if (requestParameters['versionNumber'] == null) {
            throw new runtime.RequiredError(
                'versionNumber',
                'Required parameter "versionNumber" was null or undefined when calling getArticleVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/articles/{articleId}/versions/{versionNumber}`;
        urlPath = urlPath.replace(`{${"articleId"}}`, encodeURIComponent(String(requestParameters['articleId'])));
        urlPath = urlPath.replace(`{${"versionNumber"}}`, encodeURIComponent(String(requestParameters['versionNumber'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleVersionResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific version of an article with content.
     * Get version
     */
    async getArticleVersion(requestParameters: GetArticleVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArticleVersionResponse> {
        const response = await this.getArticleVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get paginated history of versions for an article (without content).
     * List versions
     */
    async listArticleVersionsRaw(requestParameters: ListArticleVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedArticleVersionResponse>> {
        if (requestParameters['articleId'] == null) {
            throw new runtime.RequiredError(
                'articleId',
                'Required parameter "articleId" was null or undefined when calling listArticleVersions().'
            );
        }

        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError(
                'pageable',
                'Required parameter "pageable" was null or undefined when calling listArticleVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/articles/{articleId}/versions`;
        urlPath = urlPath.replace(`{${"articleId"}}`, encodeURIComponent(String(requestParameters['articleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedArticleVersionResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated history of versions for an article (without content).
     * List versions
     */
    async listArticleVersions(requestParameters: ListArticleVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedArticleVersionResponse> {
        const response = await this.listArticleVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
