/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArticleDetailResponse,
  CreateArticleRequest,
  ErrorResponse,
  Pageable,
  PaginatedArticleResponse,
  UpdateArticleRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    ArticleDetailResponseFromJSON,
    ArticleDetailResponseToJSON,
    CreateArticleRequestFromJSON,
    CreateArticleRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PageableFromJSON,
    PageableToJSON,
    PaginatedArticleResponseFromJSON,
    PaginatedArticleResponseToJSON,
    UpdateArticleRequestFromJSON,
    UpdateArticleRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface CreateArticleOperationRequest {
    createArticleRequest: CreateArticleRequest;
}

export interface DeleteArticleRequest {
    id: number;
}

export interface GetArticleRequest {
    id: number;
}

export interface ListArticlesRequest {
    pageable: Pageable;
}

export interface UpdateArticleOperationRequest {
    id: number;
    updateArticleRequest: UpdateArticleRequest;
}

/**
 * 
 */
export class ArticlesApi extends runtime.BaseAPI {

    /**
     * Create a new article
     * Create article
     */
    async createArticleRaw(requestParameters: CreateArticleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArticleDetailResponse>> {
        if (requestParameters['createArticleRequest'] == null) {
            throw new runtime.RequiredError(
                'createArticleRequest',
                'Required parameter "createArticleRequest" was null or undefined when calling createArticle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/articles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateArticleRequestToJSON(requestParameters['createArticleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleDetailResponseFromJSON(jsonValue));
    }

    /**
     * Create a new article
     * Create article
     */
    async createArticle(requestParameters: CreateArticleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArticleDetailResponse> {
        const response = await this.createArticleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an article
     * Delete article
     */
    async deleteArticleRaw(requestParameters: DeleteArticleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteArticle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/articles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an article
     * Delete article
     */
    async deleteArticle(requestParameters: DeleteArticleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteArticleRaw(requestParameters, initOverrides);
    }

    /**
     * Get an article by ID
     * Get article
     */
    async getArticleRaw(requestParameters: GetArticleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArticleDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getArticle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/articles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get an article by ID
     * Get article
     */
    async getArticle(requestParameters: GetArticleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArticleDetailResponse> {
        const response = await this.getArticleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List articles with pagination
     * List articles
     */
    async listArticlesRaw(requestParameters: ListArticlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedArticleResponse>> {
        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError(
                'pageable',
                'Required parameter "pageable" was null or undefined when calling listArticles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/articles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedArticleResponseFromJSON(jsonValue));
    }

    /**
     * List articles with pagination
     * List articles
     */
    async listArticles(requestParameters: ListArticlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedArticleResponse> {
        const response = await this.listArticlesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update article fields
     * Update article
     */
    async updateArticleRaw(requestParameters: UpdateArticleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArticleDetailResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateArticle().'
            );
        }

        if (requestParameters['updateArticleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateArticleRequest',
                'Required parameter "updateArticleRequest" was null or undefined when calling updateArticle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/articles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateArticleRequestToJSON(requestParameters['updateArticleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleDetailResponseFromJSON(jsonValue));
    }

    /**
     * Update article fields
     * Update article
     */
    async updateArticle(requestParameters: UpdateArticleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArticleDetailResponse> {
        const response = await this.updateArticleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
