/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTicketCommentRequest,
  ErrorResponse,
  Pageable,
  PaginatedTicketCommentResponse,
  TicketCommentResponse,
  UpdateTicketCommentRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    CreateTicketCommentRequestFromJSON,
    CreateTicketCommentRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PageableFromJSON,
    PageableToJSON,
    PaginatedTicketCommentResponseFromJSON,
    PaginatedTicketCommentResponseToJSON,
    TicketCommentResponseFromJSON,
    TicketCommentResponseToJSON,
    UpdateTicketCommentRequestFromJSON,
    UpdateTicketCommentRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface CreateTicketCommentOperationRequest {
    ticketId: number;
    createTicketCommentRequest: CreateTicketCommentRequest;
}

export interface DeleteTicketCommentRequest {
    ticketId: number;
    commentNumber: number;
}

export interface ListTicketCommentsRequest {
    ticketId: number;
    pageable: Pageable;
}

export interface UpdateTicketCommentOperationRequest {
    ticketId: number;
    commentNumber: number;
    updateTicketCommentRequest: UpdateTicketCommentRequest;
}

/**
 * 
 */
export class TicketCommentsApi extends runtime.BaseAPI {

    /**
     * Add a comment to a ticket
     * Create comment
     */
    async createTicketCommentRaw(requestParameters: CreateTicketCommentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketCommentResponse>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling createTicketComment().'
            );
        }

        if (requestParameters['createTicketCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'createTicketCommentRequest',
                'Required parameter "createTicketCommentRequest" was null or undefined when calling createTicketComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}/comments`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTicketCommentRequestToJSON(requestParameters['createTicketCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketCommentResponseFromJSON(jsonValue));
    }

    /**
     * Add a comment to a ticket
     * Create comment
     */
    async createTicketComment(requestParameters: CreateTicketCommentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketCommentResponse> {
        const response = await this.createTicketCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a comment
     * Delete comment
     */
    async deleteTicketCommentRaw(requestParameters: DeleteTicketCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling deleteTicketComment().'
            );
        }

        if (requestParameters['commentNumber'] == null) {
            throw new runtime.RequiredError(
                'commentNumber',
                'Required parameter "commentNumber" was null or undefined when calling deleteTicketComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}/comments/{commentNumber}`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));
        urlPath = urlPath.replace(`{${"commentNumber"}}`, encodeURIComponent(String(requestParameters['commentNumber'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a comment
     * Delete comment
     */
    async deleteTicketComment(requestParameters: DeleteTicketCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketCommentRaw(requestParameters, initOverrides);
    }

    /**
     * Get paginated comments for a ticket
     * List comments
     */
    async listTicketCommentsRaw(requestParameters: ListTicketCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTicketCommentResponse>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling listTicketComments().'
            );
        }

        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError(
                'pageable',
                'Required parameter "pageable" was null or undefined when calling listTicketComments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}/comments`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTicketCommentResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated comments for a ticket
     * List comments
     */
    async listTicketComments(requestParameters: ListTicketCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTicketCommentResponse> {
        const response = await this.listTicketCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit a comment
     * Update comment
     */
    async updateTicketCommentRaw(requestParameters: UpdateTicketCommentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketCommentResponse>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling updateTicketComment().'
            );
        }

        if (requestParameters['commentNumber'] == null) {
            throw new runtime.RequiredError(
                'commentNumber',
                'Required parameter "commentNumber" was null or undefined when calling updateTicketComment().'
            );
        }

        if (requestParameters['updateTicketCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTicketCommentRequest',
                'Required parameter "updateTicketCommentRequest" was null or undefined when calling updateTicketComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}/comments/{commentNumber}`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));
        urlPath = urlPath.replace(`{${"commentNumber"}}`, encodeURIComponent(String(requestParameters['commentNumber'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTicketCommentRequestToJSON(requestParameters['updateTicketCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketCommentResponseFromJSON(jsonValue));
    }

    /**
     * Edit a comment
     * Update comment
     */
    async updateTicketComment(requestParameters: UpdateTicketCommentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketCommentResponse> {
        const response = await this.updateTicketCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
