/* tslint:disable */
/* eslint-disable */
/**
 * RedSys API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTicketRequest,
  ErrorResponse,
  Pageable,
  PaginatedTicketResponse,
  TicketResponse,
  TransitionTicketRequest,
  UpdateTicketRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    CreateTicketRequestFromJSON,
    CreateTicketRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PageableFromJSON,
    PageableToJSON,
    PaginatedTicketResponseFromJSON,
    PaginatedTicketResponseToJSON,
    TicketResponseFromJSON,
    TicketResponseToJSON,
    TransitionTicketRequestFromJSON,
    TransitionTicketRequestToJSON,
    UpdateTicketRequestFromJSON,
    UpdateTicketRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface ChangeTicketStateRequest {
    ticketId: number;
    transitionTicketRequest: TransitionTicketRequest;
}

export interface CreateTicketOperationRequest {
    createTicketRequest: CreateTicketRequest;
}

export interface DeleteTicketRequest {
    ticketId: number;
}

export interface GetTicketRequest {
    ticketId: number;
}

export interface ListTicketsRequest {
    pageable: Pageable;
}

export interface UpdateTicketOperationRequest {
    ticketId: number;
    updateTicketRequest: UpdateTicketRequest;
}

/**
 * 
 */
export class TicketsApi extends runtime.BaseAPI {

    /**
     * Change the state of a ticket
     * Transition ticket state
     */
    async changeTicketStateRaw(requestParameters: ChangeTicketStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling changeTicketState().'
            );
        }

        if (requestParameters['transitionTicketRequest'] == null) {
            throw new runtime.RequiredError(
                'transitionTicketRequest',
                'Required parameter "transitionTicketRequest" was null or undefined when calling changeTicketState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}/state`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransitionTicketRequestToJSON(requestParameters['transitionTicketRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     * Change the state of a ticket
     * Transition ticket state
     */
    async changeTicketState(requestParameters: ChangeTicketStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.changeTicketStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new ticket
     * Create ticket
     */
    async createTicketRaw(requestParameters: CreateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        if (requestParameters['createTicketRequest'] == null) {
            throw new runtime.RequiredError(
                'createTicketRequest',
                'Required parameter "createTicketRequest" was null or undefined when calling createTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTicketRequestToJSON(requestParameters['createTicketRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     * Create a new ticket
     * Create ticket
     */
    async createTicket(requestParameters: CreateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.createTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a ticket
     * Delete ticket
     */
    async deleteTicketRaw(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling deleteTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a ticket
     * Delete ticket
     */
    async deleteTicket(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketRaw(requestParameters, initOverrides);
    }

    /**
     * Get a ticket by ID
     * Get ticket
     */
    async getTicketRaw(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling getTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     * Get a ticket by ID
     * Get ticket
     */
    async getTicket(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.getTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List tickets with pagination
     * List tickets
     */
    async listTicketsRaw(requestParameters: ListTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTicketResponse>> {
        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError(
                'pageable',
                'Required parameter "pageable" was null or undefined when calling listTickets().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTicketResponseFromJSON(jsonValue));
    }

    /**
     * List tickets with pagination
     * List tickets
     */
    async listTickets(requestParameters: ListTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTicketResponse> {
        const response = await this.listTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update ticket fields
     * Update ticket
     */
    async updateTicketRaw(requestParameters: UpdateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling updateTicket().'
            );
        }

        if (requestParameters['updateTicketRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTicketRequest',
                'Required parameter "updateTicketRequest" was null or undefined when calling updateTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tickets/{ticketId}`;
        urlPath = urlPath.replace(`{${"ticketId"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTicketRequestToJSON(requestParameters['updateTicketRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     * Update ticket fields
     * Update ticket
     */
    async updateTicket(requestParameters: UpdateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.updateTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
